version: "3.9"
services:
  db:
    image: postgres:16
    container_name: bitvavo_tradingbot_db
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: traderpwd
      POSTGRES_DB: trading
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
volumes:
  pgdata:
